### ISSUE TITLE
Cannot connect Sidechain to Mainchain with regtest=1

### ISSUE THREAD

**Issue by nchashch** [drivechain-project/sidechains#102]
drivenet.conf
```conf
rpcuser=drivenet
rpcpassword=drivechain
server=1
regtest=1
```

testchain.conf
```conf
rpcuser=drivenet
rpcpassword=drivechain
regtest=1
```
If `regtest=1` is set I get
```
The sidechain has failed to connect to the mainchain!
This may be due to configuration issues. Please check that you have set up configuration files.
...
```
popup message.

Without `regtest=1` set sidechain connects to mainchain, no problem.

I compiled both sidechain and mainchain software from source, on Arch linux. But I could still reproduce the same problem with drivechain-0.30.00 and testchain-4.01.00 binary releases.

**Comment by CryptAxe** [comment]
Thanks for pointing out the lack of documentation for this! I'll figure out somewhere to put this information so that people who want to test with the mainchain in regtest mode aren't confused. 

I already answered you on our telegram chat but I'm updating this issue for anyone else who happens to see it. 

To connect to a mainchain node that is using regtest you must also set these parameters on the sidechain: 

```
--mainchainregtest
--mainchainrpcport=18443
```

So when you're running the sidechain it might look something like this:
```
./src/qt/testchain-qt --mainchainregtest --mainchainrpcport=18443
```

Or you can add these settings to your configuration file.
